oslib: fix asprintf build failure
oslib/asprintf.h needs to include <stdarg.h> for va_list.
This started to appear on NetBSD since
38b00241e3("num2str(): Use asprintf() instead of malloc()").

--
In file included from lib/num2str.c:7:0:
lib/../oslib/asprintf.h:5:45: error: unknown type name 'va_list'; did you mean '__va_list'?
 int vasprintf(char **strp, const char *fmt, va_list ap);
                                             ^~~~~~~
                                             __va_list
    CC lib/pattern.o
gmake: *** [Makefile:447: lib/num2str.o] Error 1

Signed-off-by: Tomohiro Kusumi <kusumi.tomohiro@gmail.com>